function build_friction_rt_model(model_name)
%BUILD_FRICTION_RT_MODEL Create a Simulink model matching the Python replay logic.
%
% Recommended usage:
%   import_online_data
%   build_friction_rt_model
%   sim('friction_rt_online_generated')
%
% This version is intended to reduce mismatch against the Python script:
% - Fixed-step discrete solver
% - Fixed-step size automatically derived from base workspace variable t
% - StopTime automatically derived from t(end)
% - From Workspace interpolation disabled
% - Same residual, friction law, filtered derivative, windowed error logic,
%   and F0 slow update structure as the Python version.

if nargin < 1 || isempty(model_name)
    model_name = 'friction_rt_online_generated';
end

if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

if exist([model_name '.slx'], 'file')
    delete([model_name '.slx']);
end

prepare_base_timing_defaults();

new_system(model_name);
open_system(model_name);

set_model_solver_and_callbacks(model_name);

layout = get_layout();

add_top_level_ports(model_name, layout);
add_parameter_constants(model_name, layout);
add_signal_preprocess(model_name, layout);
add_residual_calculation(model_name, layout);
add_analytic_friction_model(model_name, layout);
add_error_preprocess(model_name, layout);
add_parameter_update(model_name, layout);
add_f0_state(model_name, layout);
wire_top_level(model_name);

Simulink.BlockDiagram.arrangeSystem(model_name);
save_system(model_name);

fprintf('Created Simulink model: %s.slx\n', model_name);
fprintf('Before simulation, run import_online_data so t, Omega_sig, Torque_Hand_sig, and AimiCurrent_sig exist.\n');
fprintf('Model uses StopTime = stop_t and FixedStep = dt_sim. These are refreshed from t at simulation initialization.\n');

end

function prepare_base_timing_defaults()
if evalin('base', 'exist(''t'', ''var'')')
    try
        t_base = evalin('base', 't(:)');
        t_base = t_base(isfinite(t_base));
        if numel(t_base) >= 2
            dt_vec = diff(t_base);
            dt_vec = dt_vec(isfinite(dt_vec) & dt_vec > 0);
            if ~isempty(dt_vec)
                assignin('base', 'dt_sim', median(dt_vec));
                assignin('base', 'stop_t', t_base(end));
                return;
            end
        end
    catch
    end
end

assignin('base', 'dt_sim', 0.01);
assignin('base', 'stop_t', 100);
end

function set_model_solver_and_callbacks(model_name)
init_code = [
"if exist('t','var')" newline ...
"    tt = t(:);" newline ...
"    tt = tt(isfinite(tt));" newline ...
"    if numel(tt) >= 2" newline ...
"        dtt = diff(tt);" newline ...
"        dtt = dtt(isfinite(dtt) & dtt > 0);" newline ...
"        if ~isempty(dtt)" newline ...
"            dt_sim = median(dtt);" newline ...
"            stop_t = tt(end) - 0.5 * median(dtt);" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"if ~exist('dt_sim','var') || ~isfinite(dt_sim) || dt_sim <= 0" newline ...
"    dt_sim = 0.01;" newline ...
"end" newline ...
"if ~exist('stop_t','var') || ~isfinite(stop_t) || stop_t <= 0" newline ...
"    stop_t = 100;" newline ...
"end" newline ...
];

set_param(model_name, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'dt_sim', ...
    'StopTime', 'stop_t', ...
    'InitFcn', char(init_code));
end

function layout = get_layout()
layout.in_x = 40;
layout.ws_x = 150;
layout.const_x = 40;
layout.sub_x = 300;
layout.out_x = 1000;

layout.tas_y = 60;
layout.motor_y = 120;
layout.omega_y = 180;
layout.temp_y = 240;

layout.const0_y = 340;
layout.const_dy = 50;

layout.pre_y = 40;
layout.residual_y = 220;
layout.friction_y = 420;
layout.err_y = 650;
layout.state_y = 850;
layout.update_y = 1020;
end

function add_top_level_ports(model_name, layout)
add_block('simulink/Sources/In1', [model_name '/TAS_Torque'], ...
    'Position', [layout.in_x layout.tas_y layout.in_x+30 layout.tas_y+20]);
add_block('simulink/Sources/In1', [model_name '/Motor_Input'], ...
    'Position', [layout.in_x layout.motor_y layout.in_x+30 layout.motor_y+20]);
add_block('simulink/Sources/In1', [model_name '/HwAngVel_Deg_s'], ...
    'Position', [layout.in_x layout.omega_y layout.in_x+30 layout.omega_y+20]);
add_block('simulink/Sources/In1', [model_name '/MCU_Temperature'], ...
    'Position', [layout.in_x layout.temp_y layout.in_x+30 layout.temp_y+20]);

add_from_workspace(model_name, 'From Workspace',  'Angle_sig',           [layout.ws_x layout.tas_y-5       layout.ws_x+105 layout.tas_y+25]);
add_from_workspace(model_name, 'From Workspace1', 'Omega_sig',           [layout.ws_x layout.motor_y-5     layout.ws_x+105 layout.motor_y+25]);
add_from_workspace(model_name, 'From Workspace2', 'Torque_Hand_sig',     [layout.ws_x layout.omega_y-5     layout.ws_x+105 layout.omega_y+25]);
add_from_workspace(model_name, 'From Workspace3', 'Torque_Motor_sig',    [layout.ws_x layout.const0_y+250  layout.ws_x+105 layout.const0_y+280]);
add_from_workspace(model_name, 'From Workspace4', 'AimiCurrent_sig',     [layout.ws_x layout.const0_y+300  layout.ws_x+105 layout.const0_y+330]);
add_from_workspace(model_name, 'From Workspace5', 'Ts_runtime_sig',      [layout.ws_x layout.const0_y+350  layout.ws_x+105 layout.const0_y+380]);
add_from_workspace(model_name, 'From Workspace6', 'Tfilter_runtime_sig', [layout.ws_x layout.const0_y+400  layout.ws_x+105 layout.const0_y+430]);

add_block('simulink/Sources/Clock', [model_name '/Clock'], ...
    'Position', [layout.ws_x layout.const0_y+460 layout.ws_x+40 layout.const0_y+490]);

add_block('simulink/Sinks/Out1', [model_name '/omega_used'], ...
    'Position', [layout.out_x 70 layout.out_x+30 90]);
add_block('simulink/Sinks/Out1', [model_name '/alpha_used'], ...
    'Position', [layout.out_x 120 layout.out_x+30 140]);
add_block('simulink/Sinks/Out1', [model_name '/residual'], ...
    'Position', [layout.out_x 280 layout.out_x+30 300]);
add_block('simulink/Sinks/Out1', [model_name '/friction_hat'], ...
    'Position', [layout.out_x 460 layout.out_x+30 480]);
add_block('simulink/Sinks/Out1', [model_name '/e_raw'], ...
    'Position', [layout.out_x 680 layout.out_x+30 700]);
add_block('simulink/Sinks/Out1', [model_name '/e_slow'], ...
    'Position', [layout.out_x 730 layout.out_x+30 750]);
add_block('simulink/Sinks/Out1', [model_name '/update_enable'], ...
    'Position', [layout.out_x 780 layout.out_x+30 800]);
add_block('simulink/Sinks/Out1', [model_name '/freeze_active'], ...
    'Position', [layout.out_x 830 layout.out_x+30 850]);
add_block('simulink/Sinks/Out1', [model_name '/count_valid_out'], ...
    'Position', [layout.out_x 880 layout.out_x+30 900]);
add_block('simulink/Sinks/Out1', [model_name '/win_elapsed_out'], ...
    'Position', [layout.out_x 930 layout.out_x+30 950]);
add_block('simulink/Sinks/Out1', [model_name '/F0_live'], ...
    'Position', [layout.out_x 1000 layout.out_x+30 1020]);

add_block('simulink/Sinks/Display', [model_name '/F0_Display'], ...
    'Position', [layout.out_x+80 990 layout.out_x+160 1025]);
end

function add_from_workspace(model_name, block_name, variable_name, pos)
blk = [model_name '/' block_name];

add_block('simulink/Sources/From Workspace', blk, ...
    'VariableName', variable_name, ...
    'Position', pos);

% Keep interpolation ON to avoid Simulink error at the final time boundary.
% With fixed-step size matched to the data dt, this should still sample the
% original data points rather than meaningfully changing the signal.
try
    set_param(blk, 'Interpolate', 'on');
catch
end

try
    set_param(blk, 'SampleTime', 'dt_sim');
catch
end

try
    set_param(blk, 'ZeroCross', 'off');
catch
end
end

function add_parameter_constants(model_name, layout)
names = {'J_const','A_const','v0_const','C1_const','omega_eps_const', ...
         'Ts_const','Tfilter_const','F0_init_const','mu_F0_const', ...
         'F0_min_const','F0_max_const','omega_min_const','alpha_max_const', ...
         'e_clip_const','e_high_const','e_low_const','recover_needed_const', ...
         'window_duration_const','min_valid_count_const'};

values = {'0.01275','0.0016515420284122229','4.297909736633301','0.04468029364943504','0.003496480407193303', ...
          '0.05','0.25','0.4111127257347107','1e-2', ...
          '0.05','2.0','0.05','20.0', ...
          '1.0','2.0','0.2','5', ...
          '5.0','10'};

for i = 1:numel(names)
    y = layout.const0_y + (i-1) * layout.const_dy;
    add_block('simulink/Sources/Constant', [model_name '/' names{i}], ...
        'Value', values{i}, ...
        'SampleTime', 'inf', ...
        'Position', [layout.const_x y layout.const_x+90 y+25]);
end
end

function add_signal_preprocess(model_name, layout)
sub = [model_name '/Signal_Preprocess'];
add_block('simulink/Ports & Subsystems/Subsystem', sub, ...
    'Position', [layout.sub_x layout.pre_y layout.sub_x+250 layout.pre_y+160]);

open_system(sub);
delete_default_contents(sub);

add_block('simulink/Sources/In1', [sub '/HwAngVel_Deg_s'], ...
    'Position', [30 38 60 58]);
add_block('simulink/Sources/In1', [sub '/Ts'], ...
    'Position', [30 88 60 108]);
add_block('simulink/Sources/In1', [sub '/Tfilter'], ...
    'Position', [30 138 60 158]);

add_block('simulink/Math Operations/Gain', [sub '/DegToRad'], ...
    'Gain', 'pi/180', ...
    'Position', [105 35 165 61]);

add_block('simulink/User-Defined Functions/MATLAB Function', [sub '/FilteredDerivative'], ...
    'Position', [215 25 390 170]);
set_matlab_function_script([sub '/FilteredDerivative'], filtered_derivative_code());

add_block('simulink/Sinks/Out1', [sub '/omega_used'], ...
    'Position', [440 48 470 68]);
add_block('simulink/Sinks/Out1', [sub '/alpha_used'], ...
    'Position', [440 108 470 128]);

add_line(sub, 'HwAngVel_Deg_s/1', 'DegToRad/1');
add_line(sub, 'DegToRad/1', 'FilteredDerivative/1');
add_line(sub, 'Ts/1', 'FilteredDerivative/2');
add_line(sub, 'Tfilter/1', 'FilteredDerivative/3');
add_line(sub, 'DegToRad/1', 'omega_used/1');
add_line(sub, 'FilteredDerivative/1', 'alpha_used/1');
end

function add_residual_calculation(model_name, layout)
sub = [model_name '/Residual_Calculation'];
add_block('simulink/Ports & Subsystems/Subsystem', sub, ...
    'Position', [layout.sub_x layout.residual_y layout.sub_x+290 layout.residual_y+150]);

open_system(sub);
delete_default_contents(sub);

add_block('simulink/Sources/In1', [sub '/TAS_Torque'], ...
    'Position', [30 28 60 48]);
add_block('simulink/Sources/In1', [sub '/Motor_Input'], ...
    'Position', [30 78 60 98]);
add_block('simulink/Sources/In1', [sub '/alpha_used'], ...
    'Position', [30 128 60 148]);
add_block('simulink/Sources/In1', [sub '/J'], ...
    'Position', [30 178 60 198]);

add_block('simulink/Math Operations/Gain', [sub '/MotorHalfGain'], ...
    'Gain', '0.5', ...
    'Position', [105 75 165 101]);

add_block('simulink/Math Operations/Product', [sub '/InertiaTerm'], ...
    'Position', [105 160 165 205]);

add_block('simulink/Math Operations/Sum', [sub '/ResidualSum'], ...
    'Inputs', '+--', ...
    'Position', [225 74 255 150]);

add_block('simulink/Sinks/Out1', [sub '/residual'], ...
    'Position', [315 104 345 124]);

add_line(sub, 'TAS_Torque/1', 'ResidualSum/1');
add_line(sub, 'Motor_Input/1', 'MotorHalfGain/1');
add_line(sub, 'MotorHalfGain/1', 'ResidualSum/2');
add_line(sub, 'alpha_used/1', 'InertiaTerm/1');
add_line(sub, 'J/1', 'InertiaTerm/2');
add_line(sub, 'InertiaTerm/1', 'ResidualSum/3');
add_line(sub, 'ResidualSum/1', 'residual/1');
end

function add_analytic_friction_model(model_name, layout)
sub = [model_name '/Analytic_Friction_Model'];
add_block('simulink/Ports & Subsystems/Subsystem', sub, ...
    'Position', [layout.sub_x layout.friction_y layout.sub_x+390 layout.friction_y+230]);

open_system(sub);
delete_default_contents(sub);

inputs = {'omega_used','F0','A','v0','C1','omega_eps'};
for i = 1:numel(inputs)
    y = 28 + (i-1) * 45;
    add_block('simulink/Sources/In1', [sub '/' inputs{i}], ...
        'Position', [30 y 60 y+20]);
end

add_block('simulink/User-Defined Functions/MATLAB Function', [sub '/FrictionLaw'], ...
    'Position', [125 60 345 230]);
set_matlab_function_script([sub '/FrictionLaw'], friction_law_code());

add_block('simulink/Sinks/Out1', [sub '/friction_hat'], ...
    'Position', [405 133 435 153]);

for i = 1:numel(inputs)
    add_line(sub, [inputs{i} '/1'], ['FrictionLaw/' num2str(i)]);
end
add_line(sub, 'FrictionLaw/1', 'friction_hat/1');
end

function add_error_preprocess(model_name, layout)
sub = [model_name '/Error_Preprocess'];
add_block('simulink/Ports & Subsystems/Subsystem', sub, ...
    'Position', [layout.sub_x layout.err_y layout.sub_x+420 layout.err_y+210]);

open_system(sub);
delete_default_contents(sub);

inputs = {'residual','friction_hat','omega_used','alpha_used','t_now', ...
          'omega_min','alpha_max','e_clip','e_high','e_low','recover_needed', ...
          'window_duration','min_valid_count'};

for i = 1:numel(inputs)
    y = 28 + (i-1) * 30;
    add_block('simulink/Sources/In1', [sub '/' inputs{i}], ...
        'Position', [30 y 60 y+20]);
end

add_block('simulink/User-Defined Functions/MATLAB Function', [sub '/FilterError'], ...
    'Position', [125 35 345 300]);
set_matlab_function_script([sub '/FilterError'], filter_error_code());

outs = {'e_raw','e_slow','update_enable','freeze_active','count_valid_out','win_elapsed_out'};
for i = 1:numel(outs)
    y = 78 + (i-1) * 55;
    add_block('simulink/Sinks/Out1', [sub '/' outs{i}], ...
        'Position', [395 y 425 y+20]);
end

for i = 1:numel(inputs)
    add_line(sub, [inputs{i} '/1'], ['FilterError/' num2str(i)]);
end

for i = 1:numel(outs)
    add_line(sub, ['FilterError/' num2str(i)], [outs{i} '/1']);
end
end

function add_parameter_update(model_name, layout)
sub = [model_name '/Parameter_Update_Slow'];
add_block('simulink/Ports & Subsystems/Subsystem', sub, ...
    'Position', [layout.sub_x layout.update_y layout.sub_x+430 layout.update_y+190]);
set_param(sub, 'TreatAsAtomicUnit', 'on');

open_system(sub);
delete_default_contents(sub);

inputs = {'e_slow','omega_used','update_enable','omega_eps', ...
          'F0_prev','mu_F0','F0_min','F0_max'};

for i = 1:numel(inputs)
    y = 28 + (i-1) * 36;
    add_block('simulink/Sources/In1', [sub '/' inputs{i}], ...
        'Position', [30 y 60 y+20]);
end

add_block('simulink/User-Defined Functions/MATLAB Function', [sub '/UpdateF0'], ...
    'Position', [125 55 350 245]);
set_matlab_function_script([sub '/UpdateF0'], update_f0_code());

add_block('simulink/Sinks/Out1', [sub '/F0_next'], ...
    'Position', [400 128 430 148]);

for i = 1:numel(inputs)
    add_line(sub, [inputs{i} '/1'], ['UpdateF0/' num2str(i)]);
end
add_line(sub, 'UpdateF0/1', 'F0_next/1');
end

function add_f0_state(model_name, layout)
sub = [model_name '/F0_State'];
add_block('simulink/Ports & Subsystems/Subsystem', sub, ...
    'Position', [layout.sub_x layout.state_y layout.sub_x+300 layout.state_y+130]);
set_param(sub, 'TreatAsAtomicUnit', 'on');

open_system(sub);
delete_default_contents(sub);

add_block('simulink/Sources/In1', [sub '/F0_next'], ...
    'Position', [30 38 60 58]);
add_block('simulink/Sources/In1', [sub '/F0_init'], ...
    'Position', [30 88 60 108]);

add_block('simulink/Discrete/Delay', [sub '/F0_delay'], ...
    'Position', [130 30 190 80], ...
    'DelayLength', '1', ...
    'InitialConditionSource', 'Input port', ...
    'SampleTime', 'dt_sim');

add_block('simulink/Sinks/Out1', [sub '/F0_live'], ...
    'Position', [245 43 275 63]);

add_line(sub, 'F0_next/1', 'F0_delay/1');
add_line(sub, 'F0_init/1', 'F0_delay/2');
add_line(sub, 'F0_delay/1', 'F0_live/1');
end

function wire_top_level(model_name)
add_line(model_name, 'From Workspace1/1', 'Signal_Preprocess/1');
add_line(model_name, 'From Workspace5/1', 'Signal_Preprocess/2');
add_line(model_name, 'From Workspace6/1', 'Signal_Preprocess/3');

add_line(model_name, 'Signal_Preprocess/1', 'Analytic_Friction_Model/1');
add_line(model_name, 'Signal_Preprocess/2', 'Residual_Calculation/3');

add_line(model_name, 'From Workspace2/1', 'Residual_Calculation/1');
add_line(model_name, 'From Workspace4/1', 'Residual_Calculation/2');
add_line(model_name, 'J_const/1', 'Residual_Calculation/4');

add_line(model_name, 'Residual_Calculation/1', 'Error_Preprocess/1');
add_line(model_name, 'Analytic_Friction_Model/1', 'Error_Preprocess/2');
add_line(model_name, 'Signal_Preprocess/1', 'Error_Preprocess/3');
add_line(model_name, 'Signal_Preprocess/2', 'Error_Preprocess/4');
add_line(model_name, 'Clock/1', 'Error_Preprocess/5');

add_line(model_name, 'omega_min_const/1', 'Error_Preprocess/6');
add_line(model_name, 'alpha_max_const/1', 'Error_Preprocess/7');
add_line(model_name, 'e_clip_const/1', 'Error_Preprocess/8');
add_line(model_name, 'e_high_const/1', 'Error_Preprocess/9');
add_line(model_name, 'e_low_const/1', 'Error_Preprocess/10');
add_line(model_name, 'recover_needed_const/1', 'Error_Preprocess/11');
add_line(model_name, 'window_duration_const/1', 'Error_Preprocess/12');
add_line(model_name, 'min_valid_count_const/1', 'Error_Preprocess/13');

add_line(model_name, 'Error_Preprocess/2', 'Parameter_Update_Slow/1');
add_line(model_name, 'Signal_Preprocess/1', 'Parameter_Update_Slow/2');
add_line(model_name, 'Error_Preprocess/3', 'Parameter_Update_Slow/3');
add_line(model_name, 'omega_eps_const/1', 'Parameter_Update_Slow/4');
add_line(model_name, 'F0_State/1', 'Parameter_Update_Slow/5');
add_line(model_name, 'mu_F0_const/1', 'Parameter_Update_Slow/6');
add_line(model_name, 'F0_min_const/1', 'Parameter_Update_Slow/7');
add_line(model_name, 'F0_max_const/1', 'Parameter_Update_Slow/8');

add_line(model_name, 'Parameter_Update_Slow/1', 'F0_State/1');
add_line(model_name, 'F0_init_const/1', 'F0_State/2');

add_line(model_name, 'F0_State/1', 'Analytic_Friction_Model/2');
add_line(model_name, 'A_const/1', 'Analytic_Friction_Model/3');
add_line(model_name, 'v0_const/1', 'Analytic_Friction_Model/4');
add_line(model_name, 'C1_const/1', 'Analytic_Friction_Model/5');
add_line(model_name, 'omega_eps_const/1', 'Analytic_Friction_Model/6');

add_line(model_name, 'Signal_Preprocess/1', 'omega_used/1');
add_line(model_name, 'Signal_Preprocess/2', 'alpha_used/1');
add_line(model_name, 'Residual_Calculation/1', 'residual/1');
add_line(model_name, 'Analytic_Friction_Model/1', 'friction_hat/1');
add_line(model_name, 'Error_Preprocess/1', 'e_raw/1');
add_line(model_name, 'Error_Preprocess/2', 'e_slow/1');
add_line(model_name, 'Error_Preprocess/3', 'update_enable/1');
add_line(model_name, 'Error_Preprocess/4', 'freeze_active/1');
add_line(model_name, 'Error_Preprocess/5', 'count_valid_out/1');
add_line(model_name, 'Error_Preprocess/6', 'win_elapsed_out/1');
add_line(model_name, 'F0_State/1', 'F0_live/1');
add_line(model_name, 'F0_State/1', 'F0_Display/1');

add_block('simulink/Sinks/Scope', [model_name '/DiagnosticsScope'], ...
    'Position', [1180 250 1210 330], ...
    'NumInputPorts', '8');

add_line(model_name, 'Signal_Preprocess/1', 'DiagnosticsScope/1');
add_line(model_name, 'Signal_Preprocess/2', 'DiagnosticsScope/2');
add_line(model_name, 'Residual_Calculation/1', 'DiagnosticsScope/3');
add_line(model_name, 'Analytic_Friction_Model/1', 'DiagnosticsScope/4');
add_line(model_name, 'Error_Preprocess/2', 'DiagnosticsScope/5');
add_line(model_name, 'Error_Preprocess/3', 'DiagnosticsScope/6');
add_line(model_name, 'Error_Preprocess/4', 'DiagnosticsScope/7');
add_line(model_name, 'F0_State/1', 'DiagnosticsScope/8');

add_to_workspace(model_name, 'omega_used_log',       'Signal_Preprocess/1',       [1140 60 1245 90]);
add_to_workspace(model_name, 'alpha_used_log',       'Signal_Preprocess/2',       [1140 105 1245 135]);
add_to_workspace(model_name, 'residual_log',         'Residual_Calculation/1',    [1140 270 1245 300]);
add_to_workspace(model_name, 'friction_hat_log',     'Analytic_Friction_Model/1', [1140 450 1245 480]);
add_to_workspace(model_name, 'e_slow_log',           'Error_Preprocess/2',        [1140 720 1245 750]);
add_to_workspace(model_name, 'update_enable_log',    'Error_Preprocess/3',        [1140 770 1245 800]);
add_to_workspace(model_name, 'freeze_active_log',    'Error_Preprocess/4',        [1140 820 1245 850]);
add_to_workspace(model_name, 'F0_live_log',          'F0_State/1',                [1140 990 1245 1020]);
end

function add_to_workspace(model_name, var_name, src_port, pos)
blk_name = ['ToWorkspace_' var_name];
blk = [model_name '/' blk_name];

add_block('simulink/Sinks/To Workspace', blk, ...
    'VariableName', var_name, ...
    'SaveFormat', 'Structure With Time', ...
    'Position', pos);

add_line(model_name, src_port, [blk_name '/1'], 'autorouting', 'on');
end

function delete_default_contents(sub)
blocks = find_system(sub, 'SearchDepth', 1, 'Type', 'Block');
for i = 2:numel(blocks)
    delete_block(blocks{i});
end

lines = find_system(sub, 'FindAll', 'on', 'SearchDepth', 1, 'Type', 'Line');
for i = 1:numel(lines)
    delete_line(lines(i));
end
end

function set_matlab_function_script(block_path, code)
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', block_path);

if isempty(chart)
    error('Could not find MATLAB Function chart for block: %s', block_path);
end

chart.Script = char(code);
end

function code = filtered_derivative_code()
code = [ ...
"function alpha = fcn(omega, Ts, Tfilter)" newline ...
"% Same filtered derivative logic as Python." newline ...
"% alpha[k] = (omega[k] - x_prev) / Tfilter" newline ...
"% x_prev <- a*omega[k] + (1-a)*x_prev, a = Ts/Tfilter" newline ...
"persistent x_prev" newline ...
"if isempty(x_prev)" newline ...
"    x_prev = omega;" newline ...
"end" newline ...
"if ~isfinite(omega)" newline ...
"    alpha = 0.0;" newline ...
"    return;" newline ...
"end" newline ...
"if ~isfinite(Ts) || Ts <= 0.0" newline ...
"    Ts = 0.05;" newline ...
"end" newline ...
"if ~isfinite(Tfilter) || Tfilter <= 0.0" newline ...
"    Tfilter = 0.25;" newline ...
"end" newline ...
"a = Ts / max(Tfilter, 1e-6);" newline ...
"a = min(max(a, 0.0), 1.0);" newline ...
"alpha = (omega - x_prev) / max(Tfilter, 1e-6);" newline ...
"x_new = a * omega + (1.0 - a) * x_prev;" newline ...
"x_prev = x_new;" newline ...
];
end

function code = friction_law_code()
code = [ ...
"function friction_hat = fcn(omega, F0, A, v0, C1, omega_eps)" newline ...
"% friction_hat = tanh(omega/omega_eps) * (F0 + A*(1-exp(-abs(omega)/v0)) + C1*abs(omega))" newline ...
"if ~isfinite(omega) || ~isfinite(F0)" newline ...
"    friction_hat = 0.0;" newline ...
"    return;" newline ...
"end" newline ...
"if ~isfinite(A)" newline ...
"    A = 0.0;" newline ...
"end" newline ...
"if ~isfinite(v0) || v0 <= 0.0" newline ...
"    v0 = 1.0;" newline ...
"end" newline ...
"if ~isfinite(C1)" newline ...
"    C1 = 0.0;" newline ...
"end" newline ...
"if ~isfinite(omega_eps) || omega_eps <= 0.0" newline ...
"    omega_eps = 1e-6;" newline ...
"end" newline ...
"absw = abs(omega);" newline ...
"s = tanh(omega / max(omega_eps, 1e-6));" newline ...
"phi = 1.0 - exp(-absw / max(v0, 1e-6));" newline ...
"mag = F0 + A * phi + C1 * absw;" newline ...
"if mag < 0.0" newline ...
"    mag = 0.0;" newline ...
"end" newline ...
"friction_hat = s * mag;" newline ...
];
end

function code = filter_error_code()
code = [ ...
"function [e_raw, e_slow, update_enable, freeze_active, count_valid_out, win_elapsed_out] = fcn(residual, friction_hat, omega, alpha, t_now, omega_min, alpha_max, e_clip, e_high, e_low, recover_needed, window_duration, min_valid_count)" newline ...
"% Same windowed error preprocessing logic as Python." newline ...
"persistent e_hold freeze_state recover_count win_elapsed sum_mag count_valid t_prev" newline ...
"if isempty(e_hold)" newline ...
"    e_hold = 0.0;" newline ...
"    freeze_state = false;" newline ...
"    recover_count = 0;" newline ...
"    win_elapsed = 0.0;" newline ...
"    sum_mag = 0.0;" newline ...
"    count_valid = 0;" newline ...
"    t_prev = t_now;" newline ...
"end" newline ...
"if ~isfinite(residual) || ~isfinite(friction_hat) || ~isfinite(omega) || ~isfinite(alpha)" newline ...
"    e_raw = 0.0;" newline ...
"    e_slow = e_hold;" newline ...
"    update_enable = false;" newline ...
"    freeze_active = true;" newline ...
"    count_valid_out = count_valid;" newline ...
"    win_elapsed_out = win_elapsed;" newline ...
"    return;" newline ...
"end" newline ...
"if ~isfinite(t_now)" newline ...
"    t_now = t_prev;" newline ...
"end" newline ...
"dt = t_now - t_prev;" newline ...
"if ~isfinite(dt) || dt < 0.0" newline ...
"    dt = 0.0;" newline ...
"end" newline ...
"t_prev = t_now;" newline ...
"if ~isfinite(omega_min)" newline ...
"    omega_min = 0.05;" newline ...
"end" newline ...
"if ~isfinite(alpha_max) || alpha_max <= 0.0" newline ...
"    alpha_max = 20.0;" newline ...
"end" newline ...
"if ~isfinite(e_clip) || e_clip <= 0.0" newline ...
"    e_clip = 1.0;" newline ...
"end" newline ...
"if ~isfinite(e_high) || e_high <= 0.0" newline ...
"    e_high = 2.0;" newline ...
"end" newline ...
"if ~isfinite(e_low) || e_low < 0.0" newline ...
"    e_low = 0.2;" newline ...
"end" newline ...
"if ~isfinite(recover_needed) || recover_needed < 1.0" newline ...
"    recover_needed = 5.0;" newline ...
"end" newline ...
"if ~isfinite(window_duration) || window_duration <= 0.0" newline ...
"    window_duration = 5.0;" newline ...
"end" newline ...
"if ~isfinite(min_valid_count) || min_valid_count < 1.0" newline ...
"    min_valid_count = 10.0;" newline ...
"end" newline ...
"e_raw = residual - friction_hat;" newline ...
"e_mag = abs(residual) - abs(friction_hat);" newline ...
"trusted_sample = (abs(omega) > omega_min) && (abs(alpha) < alpha_max);" newline ...
"anomaly = (abs(e_raw) > e_high) || (abs(alpha) > alpha_max);" newline ...
"recovered = trusted_sample && (abs(e_raw) < e_low);" newline ...
"if ~freeze_state && anomaly" newline ...
"    freeze_state = true;" newline ...
"    recover_count = 0;" newline ...
"elseif freeze_state" newline ...
"    if recovered" newline ...
"        recover_count = recover_count + 1;" newline ...
"        if recover_count >= round(recover_needed)" newline ...
"            freeze_state = false;" newline ...
"            recover_count = 0;" newline ...
"        end" newline ...
"    else" newline ...
"        recover_count = 0;" newline ...
"    end" newline ...
"end" newline ...
"sample_ok = trusted_sample && ~freeze_state;" newline ...
"e_used = e_mag;" newline ...
"if e_used > e_clip" newline ...
"    e_used = e_clip;" newline ...
"elseif e_used < -e_clip" newline ...
"    e_used = -e_clip;" newline ...
"end" newline ...
"update_enable = false;" newline ...
"win_elapsed = win_elapsed + dt;" newline ...
"if sample_ok" newline ...
"    sum_mag = sum_mag + e_used;" newline ...
"    count_valid = count_valid + 1;" newline ...
"end" newline ...
"if win_elapsed >= max(window_duration, 1e-6)" newline ...
"    if count_valid >= max(1, round(min_valid_count))" newline ...
"        e_hold = sum_mag / count_valid;" newline ...
"        update_enable = true;" newline ...
"    end" newline ...
"    win_elapsed = 0.0;" newline ...
"    sum_mag = 0.0;" newline ...
"    count_valid = 0;" newline ...
"end" newline ...
"e_slow = e_hold;" newline ...
"freeze_active = freeze_state;" newline ...
"count_valid_out = count_valid;" newline ...
"win_elapsed_out = win_elapsed;" newline ...
];
end

function code = update_f0_code()
code = [ ...
"function F0_next = fcn(e_slow, omega, update_enable, omega_eps, F0_prev, mu_F0, F0_min, F0_max)" newline ...
"% Batch F0 adaptation using windowed magnitude-domain error." newline ...
"% omega and omega_eps are kept as inputs for interface compatibility, but F0 update is sign-independent." newline ...
"F0_next = F0_prev;" newline ...
"if ~isfinite(F0_next)" newline ...
"    F0_next = 0.4111127257347107;" newline ...
"end" newline ...
"if ~isfinite(mu_F0)" newline ...
"    mu_F0 = 1e-2;" newline ...
"end" newline ...
"if ~isfinite(F0_min)" newline ...
"    F0_min = 0.05;" newline ...
"end" newline ...
"if ~isfinite(F0_max)" newline ...
"    F0_max = 2.0;" newline ...
"end" newline ...
"if update_enable && isfinite(e_slow)" newline ...
"    F0_next = F0_prev + mu_F0 * e_slow;" newline ...
"end" newline ...
"if F0_next < F0_min" newline ...
"    F0_next = F0_min;" newline ...
"elseif F0_next > F0_max" newline ...
"    F0_next = F0_max;" newline ...
"end" newline ...
];
end